In [1]:
import numpy as np

## NUMPY INDEXING AND SLICING OF VECTORS

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[9]

np.int64(20)

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [7]:
arr[:5]

array([11, 12, 13, 14, 15])

In [10]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[1::2]

array([12, 14, 16, 18, 20])

## NUMPY INDEXING AND SLICING OF MATRIX

In [15]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr[0]

array([1, 2, 3, 4, 5])

In [19]:
int(arr[0,1])

2

In [21]:
int(arr[5,4])

30

In [23]:
int(arr[0,0])

1

In [26]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [28]:
slice = arr[0:2,0:2]
slice

array([[1, 2],
       [6, 7]])

In [30]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [32]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## BOOLEAN INDEXING

In [39]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [41]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])