In [2]:
import numpy as np

## ARRAY OPERATIONS

### Arithmetic operations

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [10]:
a1 % a2

array([1, 2, 3, 4, 5])

### Broadcasting

In [11]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [12]:
arr + 10

array([20, 30, 40, 50])

In [13]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### Deep and Shallow copy

In [16]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [19]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a[4:6] * 10

array([50, 60])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
a
b = a

In [26]:
b[0] = 99

In [28]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### MATRIX OPERATIONS 

In [30]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [31]:
A

array([[1, 2],
       [3, 4]])

In [32]:
B

array([[5, 6],
       [7, 8]])

In [36]:
# matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [37]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [39]:
A

array([[1, 2],
       [3, 4]])

In [40]:
A.T

array([[1, 3],
       [2, 4]])

## ADVANCE ARRAY MANIPULATION

### Stacking Array

In [43]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [45]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [50]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [53]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [54]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [58]:
a = np.vsplit(c,4)

In [59]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
