In [2]:
import numpy as np

Basic array creation

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2,3,4,"harshith",3.5]
a

[1, 2, 3, 4, 'harshith', 3.5]

In [6]:
np.array(a)

array(['1', '2', '3', '4', 'harshith', '3.5'], dtype='<U32')

In [7]:
l=[[1,2,3] , [4,5,6] , [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
la=np.array(l)
la

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [11]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr = np.zeros((6))
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [20]:
arr = np.linspace(1,10,2)
arr

array([ 1., 10.])