In [7]:
import numpy as np

## Basic array creation

In [8]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a = [1,2,3,4,"harshith",3.5]
a

[1, 2, 3, 4, 'harshith', 3.5]

In [10]:
np.array(a)

array(['1', '2', '3', '4', 'harshith', '3.5'], dtype='<U32')

In [11]:
l=[[1,2,3] , [4,5,6] , [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
la=np.array(l)
la

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array generation function

In [11]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr = np.zeros((6))
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [14]:
arr = np.linspace(1,10,2)
arr

array([ 1., 10.])

In [15]:
arr = np.linspace(1,20,5)
arr

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

## Random generation function

In [6]:
np.random.rand(10)

array([0.30430851, 0.14791308, 0.28717013, 0.23833497, 0.07769349,
       0.1645654 , 0.07102256, 0.5301103 , 0.22719314, 0.75199603])

In [14]:
np.random.randn(10)

array([-0.78264181, -0.45449974, -0.89902218,  0.55946151,  2.3277062 ,
       -0.65050612,  1.7461545 ,  0.60391517,  0.78712848,  0.00258154])

In [15]:
np.random.randint(10,20,10)

array([16, 15, 14, 13, 18, 18, 18, 17, 19, 19], dtype=int32)

## Array attributes

In [38]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.shape

(3, 3)

In [40]:
arr.size

9

In [41]:
arr.dtype

dtype('int64')

## Arrray methods

In [44]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [45]:
arr.sum()

np.int64(45)

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [48]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [49]:
arr.mean()

np.float64(5.0)

In [50]:
arr.std()

np.float64(2.581988897471611)

In [51]:
arr.argmax()

np.int64(8)

In [52]:
arr.argmin()

np.int64(0)

## Reshaping and resizing

In [55]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [58]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])