In [1]:
import numpy as np

In [3]:
arr  = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
a=[1,2,3,4,"asd"]
a

[1, 2, 3, 4, 'asd']

In [6]:
arr  = np.array(a)
arr

array(['1', '2', '3', '4', 'asd'], dtype='<U21')

In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
arr = np.linspace(2,10,5)
arr

array([ 2.,  4.,  6.,  8., 10.])

In [18]:
np.random.rand(10)

array([0.12620105, 0.40670807, 0.30449618, 0.47302912, 0.861623  ,
       0.98642455, 0.24079138, 0.97517775, 0.2180846 , 0.16516306])

In [19]:
np.random.randn(10)

array([-0.13339981,  2.02896328, -2.10542757, -0.32344969, -2.63027219,
       -0.76922354,  0.33497906,  1.47215204,  0.34454622, -0.84216346])

In [21]:
np.random.randint(10,20,10)

array([16, 14, 13, 12, 17, 19, 14, 15, 16, 18], dtype=int32)

In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.shape

(3, 3)

In [25]:
arr.size

9

In [26]:
arr.dtype

dtype('int64')

In [28]:
int(arr.min())

1

In [29]:
int(arr.max())

9

In [30]:
int(arr.sum())

45

In [32]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [34]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [36]:
int(arr.mean())

5

In [37]:
int(arr.std())

2

In [38]:
arr.argmax()

np.int64(8)

In [39]:
arr.argmin()

np.int64(0)

In [41]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])